Fixed errors for the functions and their test files
harvard-edtech/dce-reactkit pull request #13
Opened 2024-07-30 16:25 UTC by leishab

2024-07-30 16:39 UTC, gabeabrams commented
In `/src/index.ts`, import your helper functions in the section where all the helpers are imported, then export your helper functions below in the section marked by `// Helpers`

2024-08-05 19:26 UTC, leishab commented
**findURLs:**
This function iterates through and identifies URLs in a block of text, after which it returns their start and end index. The function contains a while loop to use the regex to locate and then match the URL(s) within the block of text, after which the start and end index of the URL is found and pushed to the found array, which is returned to the user. 

The test file for this function involves various test cases which test whether the function returns the correct start and end indices for the correctly identified URLs, edge cases such as when the URL has a trailing or leading punctuation mark and returns empty array for strings without valid URLs or for invalid input formats.

**toTitleCase:**
This function changes any input string so that it adheres to the rules of Chicago Title Case Style. Before this function can proceed to do this, it first makes sure to throw an error if the input is undefined, null or not a string. It then converts the entire input string to lowercase and splits it into separate words. It maps over this string and capitalizes the first and last word, and any word in the input that is not a part of the lowercaseWords list. It then puts the words back together and returns the new string that has been converted to Chicago Title Case Style.

It also includes the test file to validate the function's behavior. It first tests the function with some tests that would return valid, some edge cases such as single letters, all capitalized strings etc. and tests whether the appropriate error is thrown incase an input is invalid
 
 **isValid**:
This function checks if a given input string is a valid URL. It does so by using the input URL to create a URL object and using the URL constructor to throw an error if the URL is invalid. 

It also includes a test file to verify the function's correctness. The test file consists of many examples of URLs that would be considered valid, as well as invalid.

2024-08-20 18:50 UTC, gabeabrams reviewed
More comments

2024-08-20 18:52 UTC, gabeabrams commented on src/helpers/validators/isValid.ts
> +    if (!['https:', 'http:', 'file:', 'ftp:'].includes(parsed.protocol)) {
Only https and http

2024-08-20 18:53 UTC, gabeabrams commented on src/helpers/validators/isValid.ts
> +    if (!parsed.hostname || parsed.hostname.startsWith('.')) {
`parsed.hostname.trim().length === 0

2024-08-20 18:53 UTC, gabeabrams commented on src/helpers/validators/isValid.ts
> +    if (!parsed.hostname || parsed.hostname.endsWith('.')) {
Combine with above

2024-08-20 18:54 UTC, gabeabrams commented on src/helpers/validators/isValid.ts
> +    if (/(\.\.)/.test(parsed.hostname)) {
parsed.hostname.includes('..')

2024-08-20 18:55 UTC, gabeabrams commented on src/helpers/validators/isValid.ts
> +    if (!parsed.hostname || parsed.hostname.endsWith('.') || /^\d+$/.test(parsed.hostname)) {
This doesn't seem necessary

2024-08-20 18:55 UTC, gabeabrams commented on src/helpers/validators/isValid.ts
> +    if (parsed.port && !/^\d+$/.test(parsed.port)) {
`Number.isNaN(Number.parseInt(parsed.port, 10))`

2024-08-20 18:56 UTC, gabeabrams commented on src/helpers/validators/toTitleCase.ts
> +const toTitleCase = (input: any): string => {
Input should be a string

2024-08-20 18:56 UTC, gabeabrams commented on src/helpers/validators/toTitleCase.ts
> +  if (typeof input !== 'string') throw new Error('Input is a number. It must be a string');
We don't need these checks

2024-08-20 18:56 UTC, gabeabrams commented on src/helpers/validators/toTitleCase.ts
> +  ];
These should exist outside the function

2024-08-20 18:57 UTC, gabeabrams commented on src/helpers/validators/toTitleCase.ts
> +    .join(' ');
Formatting

```ts

return (
  input
    // The entire input string is converted to lowercase
    .toLowerCase()
    // Splits string into separate words
    .split(' ')
    .map((word, index, words) => {
      // Capitalize the first, last word, and any word in the input that is not a part of the lowercaseWords list
      return (index === 0 || index === words.length - 1 || !lowerCaseWords.includes(word)
        ? `${word.charAt(0).toUpperCase()}${word.slice(1)}`
        : word);
    })
    // Join the words back
    .join(' ')
);
```

2024-08-20 18:58 UTC, gabeabrams commented on src/helpers/validators/toTitleCase.ts
> +        : word);
One item per line

```ts
return (
  (index === 0 || index === words.length - 1 || !lowerCaseWords.includes(word))
    ? `${word.charAt(0).toUpperCase()}${word.slice(1)}`
    : word
);
```

2024-08-20 18:58 UTC, gabeabrams requested changes
See comments. Super close!

2024-08-29 14:09 UTC, gabeabrams commented on src/helpers/validators/toTitleCase.test.ts
> +};
I don't understand this

2025-03-24 21:27 UTC, closed without merging